# Generated by Django 2.2 on 2020-05-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotcity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'hotcity',
                'managed': False,
            },
        ),
    ]
